'use strict'

// Assignments of constants
const
    messageContainer = document.getElementsByClassName('moyenne-message')[0],
    averageContainer = document.getElementsByClassName('moyenne-note')[0],
    errorContainer = document.getElementsByClassName('erreur')[0],
    errorContent = "Un ou plusieurs nombres ne sont pas corrects";

// Function to calculate the average
function averageCalc() {
    // Use of 'Array.from' to transform fake array generated by DOM
    let arr = Array.from(document.getElementsByClassName('note'));
    // Use of .map method to classify each item by value
    let values = arr.map((elt)=>parseInt(elt.value));
    // Use of .reduce method to sum each value
    let totalNotes = values.reduce((prev, cur) => prev + cur);
    // Let's check if each value is a number || if each of them are between 0 & 20
    if (values.filter((a)=>isNaN(a)).length !== 0 || values.filter((a)=>a<0).length !== 0 || values.filter((a)=>a>20).length !== 0){
        showError(errorContent);
    } else {
        let moyenne = totalNotes / arr.length;
        showAverage(moyenne);
        arr.forEach(function(i){i.value = ""});
    };
};

// Function for hide/show contents when error happened
function showError(msg){
    messageContainer.style.display = "none";
    averageContainer.style.display = "none";
    errorContainer.style.display = "flex";
    errorContainer.innerHTML = msg;
};

// Function for hide/show contents when average is defined
function showAverage(avg){
    messageContainer.style.display = "flex";
    averageContainer.style.display = "flex";
    errorContainer.style.display = "none";
    averageContainer.innerHTML = avg + "/20";
};
